figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotBubbleMarket_PanelbyCondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotBubbleMarket_PanelbyConditionOT.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotBubbleMarket_PanelbyConditionSaline.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotM1M2choiceOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotM1M2choiceOTsaline_allPanelbyconditionV2.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotM1M2choice_all.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotM1M2choice_allPanelbyconditionV2.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotM1M2rew2choice_all.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotMarketType.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoiceOTsaline_allPanelbycondition.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_ai.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_all.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_allPanel.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_allPanelbyconditionFM.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_decoy.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_live.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoice_replay.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionChoiceconditions.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotOptionM2ChoiceOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioDiff_PanelbyCondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioDiff_PanelbyConditionFM.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeChoice.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeChoiceFM.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeChoiceV2.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeM1M2.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeM1M2conditions.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotPortfolioTypeM1M2conditionsFM.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRepeatOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRepeat_PanelbyCondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRepeat_PanelbyConditionFM.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRepeats.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRepeatsM2.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRew1onOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRew2offOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotRew2onOTsaline_allPanelbycondition.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotSpikeRaster_.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuff.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffJustOT.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffJustOTrew2.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffJustOTtrialstart.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffJustSaline.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffOTSalineconditions.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffOTSalineconditions_subplots.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffOTconditions.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffP15.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffconditions.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffconditionsOT.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffconditionsRew2.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffconditionsTrialOn.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffdivpershare.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffdivpershareM2.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffdivpersharev2.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotStuffdivpersharev2FM.m');
figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\plotTrialStartOTsaline_allPanelbycondition.m');
% figure; run('C:\Users\plattlab\MSM\scripts\legacy\am_orig_codes_250602\ploterr.m');